# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('btag', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('author', models.CharField(db_index=True, max_length=63)),
                ('publisher', models.CharField(db_index=True, max_length=63)),
                ('producer', models.CharField(max_length=63, null=True)),
                ('original_title', models.CharField(max_length=63, null=True)),
                ('translator', models.CharField(max_length=63, null=True)),
                ('publish_time', models.DateTimeField()),
                ('page_number', models.IntegerField()),
                ('price', models.FloatField()),
                ('pack', models.CharField(max_length=63, null=True)),
                ('series', models.CharField(max_length=63, null=True)),
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('subtitle', models.CharField(max_length=63, null=True)),
                ('title', models.CharField(db_index=True, max_length=63)),
                ('rating_num', models.FloatField()),
                ('book_summary', models.TextField()),
                ('author_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SmallTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('stag', models.CharField(max_length=31, unique=True)),
                ('btag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.BigTag')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='stag',
            field=models.ManyToManyField(to='spider.SmallTag'),
        ),
    ]
